const { chromium } = require(process.env.NEBULA_PLAYWRIGHT_PATH || 'playwright');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
 const browser = await chromium.launch({channel: 'msedge', headless:true});
 const page = await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000/design-preview');
 await page.getByRole('heading',{name:'El arte de observar',exact:true}).first().waitFor();
 await page.screenshot({path:path.resolve('auditoria_astra/evidencias/catalogo-escritorio.png'),fullPage:true});
 await page.getByRole('searchbox').fill('disenar');
 if (await page.locator('.collection-item').count() !== 1) throw Error('Accent-insensitive search failed');
 await page.getByRole('searchbox').fill('ningun-titulo');
 await page.getByRole('heading',{name:'No encontramos ese título'}).waitFor();
 await page.getByRole('button',{name:'Limpiar filtros'}).click();
 await page.getByLabel('Categoría',{exact:true}).selectOption('Diseño');
 if (await page.locator('.collection-item').count() !== 2) throw Error('Category filter failed');
 await page.getByLabel('Categoría',{exact:true}).selectOption('');
 await page.getByLabel('Ordenar biblioteca').selectOption('title');
 if (!(await page.locator('.collection-item').first().innerText()).includes('Arquitectura')) throw Error('Sort failed');
 await page.getByLabel('Cambiar tema de color').click();
 await page.screenshot({path:path.resolve('auditoria_astra/evidencias/catalogo-claro.png'),fullPage:true});
 await page.getByLabel('Cambiar tema de color').click();
 await page.locator('.cinema-player').scrollIntoViewIfNeeded();
 await page.evaluate(async()=> {
   const canvas=document.createElement('canvas'); canvas.width=960;canvas.height=540;
   const ctx=canvas.getContext('2d');
   const stream=canvas.captureStream(30);
   const recorder=new MediaRecorder(stream,{mimeType:'video/webm'});const chunks=[];
   recorder.ondataavailable=e=>chunks.push(e.data);
   const done=new Promise(resolve=>recorder.onstop=resolve); recorder.start();
   const interval=setInterval(()=>{ctx.fillStyle='#25331c';ctx.fillRect(0,0,960,540);ctx.fillStyle='#dbf77e';ctx.font='54px sans-serif';ctx.fillText('NÉBULA / PRUEBA LOCAL',80,250);},30);
   await new Promise(r=>setTimeout(r,2200));recorder.stop();await done;clearInterval(interval);stream.getTracks().forEach(t=>t.stop());
   const video=document.querySelector('video');video.src=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));video.load();
 });
 await page.waitForFunction(()=>document.querySelector('video').readyState >= 2);
 await page.locator('.cinema-toolbar').getByRole('button',{name:'Reproducir',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('video').paused);
 await page.locator('.cinema-toolbar').getByRole('button',{name:'Pausar',exact:true}).click();
 await page.getByRole('button',{name:'Ajustes de reproducción'}).click();
 await page.getByLabel('Velocidad',{exact:true}).selectOption('1.5');
 if (await page.locator('video').evaluate(v=>v.playbackRate)!==1.5) throw Error('Speed failed');
 await page.getByLabel('Velocidad',{exact:true}).press('Escape');
 if (await page.locator('.cinema-settings').count()) throw Error('Escape failed');
 await page.getByRole('button',{name:'Silenciar',exact:true}).click();
 if (!await page.locator('video').evaluate(v=>v.muted)) throw Error('Mute failed');
 await page.locator('.cinema-player').focus(); await page.keyboard.press('m');
 if (await page.locator('video').evaluate(v=>v.muted)) throw Error('Keyboard mute failed');
 await page.getByRole('button',{name:'Ajustes de reproducción'}).click();
 await page.getByRole('button',{name:'Usar controles del navegador'}).click();
 if (!await page.locator('video').evaluate(v=>v.controls)) throw Error('Native fallback failed');
 await page.getByRole('button',{name:'Volver a controles Nébula'}).click();
 await page.locator('.cinema-player').screenshot({path:path.resolve('auditoria_astra/evidencias/reproductor.png')});
 const layouts=[];
 for(const width of [390,768,1440]) {
   await page.setViewportSize({width,height:900});
   await page.getByRole('searchbox').scrollIntoViewIfNeeded();
   const dimensions=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
   layouts.push(dimensions);if(dimensions.scroll>width) throw Error('Horizontal overflow '+width);
   if(width===390) { await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'})); }
   if(width===390)await page.screenshot({path:path.resolve('auditoria_astra/evidencias/catalogo-movil.png'),fullPage:true});
 }
 await page.goto('http://localhost:3000/signin');
 await page.getByRole('heading',{name:'Bienvenido de vuelta'}).waitFor();
 await page.getByRole('button',{name:'Continuar con Google'}).waitFor();
 await page.screenshot({path:path.resolve('auditoria_astra/evidencias/acceso.png'),fullPage:true});
 fs.writeFileSync('auditoria_astra/evidencias/resultado-ui.json',JSON.stringify({passed:['search accents','empty state','clear filters','categories','sort','theme','play','pause','speed','escape','mute','keyboard mute','native fallback','responsive'],layouts,errors},null,2));
 await browser.close(); console.log('UI assertions passed',JSON.stringify({layouts,errors}));
})().catch(e=>{console.error(e);process.exit(1)});
